#!/bin/bash

for d in 0025449 0025446 0025444 0025428 0025453 0025440 0025445 0025443 0025447 0025448 0025452 0025441 0025429 0025442; do

    antsApplyTransforms --default-value 0 --dimensionality 3 --float 0 --input /media/ebs/v162/dev-v162-xcp/default-pipeline/working/resting_preproc_sub-$d\_ses-1/anat_preproc_afni_0/anat_skullstrip_orig_vol/sub-$d\_ses-1_run-1_T1w_resample_calc.nii.gz --input-image-type 0 --interpolation LanczosWindowedSinc --output sub-$d\_ses-1_brain_antswarp.nii.gz --reference-image /usr/share/fsl/5.0/data/standard/MNI152_T1_2mm_brain.nii.gz --transform /media/ebs/v162/dev-v162-xcp/default-pipeline/working/resting_preproc_sub-$d\_ses-1/anat_mni_ants_register_0/calc_ants_warp/transform3Warp.nii.gz --transform /media/ebs/v162/dev-v162-xcp/default-pipeline/working/resting_preproc_sub-$d\_ses-1/anat_mni_ants_register_0/calc_ants_warp/transform2Affine.mat --transform /media/ebs/v162/dev-v162-xcp/default-pipeline/working/resting_preproc_sub-$d\_ses-1/anat_mni_ants_register_0/calc_ants_warp/transform1Rigid.mat --transform /media/ebs/v162/dev-v162-xcp/default-pipeline/working/resting_preproc_sub-$d\_ses-1/anat_mni_ants_register_0/calc_ants_warp/transform0DerivedInitialMovingTranslation.mat

    antsApplyTransforms --default-value 0 --dimensionality 3 --float 0 --input /media/ebs/v162/dev-v162-xcp/default-pipeline/working/resting_preproc_sub-$d\_ses-1/anat_preproc_afni_0/anat_skullstrip_orig_vol/sub-$d\_ses-1_run-1_T1w_resample_calc.nii.gz --input-image-type 0 --interpolation LanczosWindowedSinc --output sub-$d\_ses-1_brain_antswarp_azeez.nii.gz --reference-image /usr/share/fsl/5.0/data/standard/MNI152_T1_2mm_brain.nii.gz --transform /media/ebs/v162/dev-v162-xcp/default-pipeline/working/resting_preproc_sub-$d\_ses-1/anat_mni_ants_register_0/calc_ants_warp/transform0DerivedInitialMovingTranslation.mat --transform /media/ebs/v162/dev-v162-xcp/default-pipeline/working/resting_preproc_sub-$d\_ses-1/anat_mni_ants_register_0/calc_ants_warp/transform1Rigid.mat --transform /media/ebs/v162/dev-v162-xcp/default-pipeline/working/resting_preproc_sub-$d\_ses-1/anat_mni_ants_register_0/calc_ants_warp/transform2Affine.mat --transform /media/ebs/v162/dev-v162-xcp/default-pipeline/working/resting_preproc_sub-$d\_ses-1/anat_mni_ants_register_0/calc_ants_warp/transform3Warp.nii.gz;

done;
